# Generated by Django 4.2.8 on 2025-01-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
                ('favorite', models.BooleanField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(max_length=50)),
                ('description', models.BooleanField()),
                ('image', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=50)),
                ('sale', models.BooleanField()),
                ('title', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplybrooksapi.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplybrooksapi.genre')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplybrooksapi.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplybrooksapi.genre')),
            ],
        ),
    ]
