# Generated by Django 4.2.8 on 2025-01-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplybrooksapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
    ]
